### ISSUE TITLE
bug: search image on ubuntu

### ISSUE THREAD

**Issue by FerreroFacundo** [wejs/we-plugin-file#1]
Running on Ubuntu 14, when you try to recover an image that was previuosly uploaded you get 404.

The problem lies when the function findOne in the image.js controller searches the entry in the model, it uses the filename, but without the extension. 

to solve it, right after the line:
  var fileName = req.params.name;

(line 31) add the following:

  if (req.extension && (!req.params.name.endsWith(req.extension)))
        fileName += '.'+req.extension;

If you create a branch, i'll submit a pull request to upload this fix. 
Tests pass ok with these changes

**Comment by albertosouza** [comment]
Is working i current version, this error may be related to we.js v1.2 update

Closing this issue but feel free to reopen if need
